# Generated by Django 6.0.1 on 2026-01-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Date de référence',
                'verbose_name_plural': 'Dates de référence',
            },
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Dénomination',
                'verbose_name_plural': 'Dénominations',
            },
        ),
        migrations.CreateModel(
            name='SiteOlympique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Site olympique',
                'verbose_name_plural': 'Sites olympiques',
            },
        ),
        migrations.CreateModel(
            name='Typologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Typologie',
                'verbose_name_plural': 'Typologies',
            },
        ),
        migrations.CreateModel(
            name='SportSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.PositiveSmallIntegerField()),
                ('commune', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geo_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('informations_acces_transport', models.TextField(blank=True)),
                ('appellation', models.CharField(max_length=255)),
                ('datation', models.CharField(blank=True, max_length=150)),
                ('periode_de_construction', models.CharField(blank=True, max_length=150)),
                ('historique_et_description', models.TextField(blank=True)),
                ('credits', models.CharField(blank=True, max_length=255)),
                ('url_image', models.URLField(blank=True)),
                ('adresse_com', models.CharField(blank=True, max_length=255)),
                ('dates_reference', models.ManyToManyField(blank=True, related_name='sites', to='patrisport.datereference')),
                ('denomination', models.ManyToManyField(blank=True, related_name='sites', to='patrisport.denomination')),
                ('site_olympique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='patrisport.siteolympique')),
                ('typologie', models.ManyToManyField(blank=True, related_name='sites', to='patrisport.typologie')),
            ],
            options={
                'verbose_name': 'Site sportif',
                'verbose_name_plural': 'Sites sportifs',
            },
        ),
    ]
